- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Create db container 
      docker_container:
        name: db_test
        image: "postgres:latest"
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - "5432:5432"

      vars:
        ansible_python_interpreter: /usr/bin/python3
