- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Create db container
      docker_container:
        name: db_test
        image: "postgres:latest"
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - "5432:5432"
      vars:
        ansible_python_interpreter: /usr/bin/python3


    - name: Create keycloak container
      docker_container:
        name: keycloak_test
        image: "quay.io/keycloak/keycloak:10.0.2"
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
          - "8080:8080"
        volumes:
          - "keycloak-db:/opt/jboss/keycloak/standalone/data:rw"
      vars:
        ansible_python_interpreter: /usr/bin/python3
